/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#7a7b7b",
        surface: "#111417",
        error: "#ffb4ab",
        "on-secondary-fixed-variant": "#00497d",
        primary: "#c6c6c7",
        "secondary-fixed-dim": "#9ecaff",
        "surface-bright": "#37393d",
        "inverse-surface": "#e1e2e7",
        "inverse-on-surface": "#2e3134",
        "on-surface": "#e1e2e7",
        tertiary: "#a8c8ff",
        "on-secondary-fixed": "#001d36",
        "surface-container-low": "#191c1f",
        "surface-container-high": "#282a2e",
        "primary-fixed-dim": "#c6c6c7",
        secondary: "#9ecaff",
        background: "#111417",
        "tertiary-container": "#000e24",
        "on-tertiary-fixed-variant": "#114784",
        "tertiary-fixed": "#d5e3ff",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-container-lowest": "#0c0e12",
        "inverse-primary": "#5d5f5f",
        "on-secondary-container": "#002b4d",
        "on-secondary": "#003258",
        "surface-variant": "#323539",
        "on-error": "#690005",
        "on-background": "#e1e2e7",
        "surface-container-highest": "#323539",
        "outline-variant": "#45474b",
        "on-primary-fixed-variant": "#454747",
        "surface-dim": "#111417",
        "surface-tint": "#c6c6c7",
        "on-tertiary-fixed": "#001b3c",
        "primary-container": "#0c0e0f",
        "primary-fixed": "#e2e2e2",
        outline: "#8f9095",
        "on-surface-variant": "#c6c6cb",
        "on-tertiary": "#003061",
        "surface-container": "#1d2023",
        "secondary-fixed": "#d1e4ff",
        "secondary-container": "#1e95f2",
        "on-primary": "#2f3131",
        "on-primary-fixed": "#1a1c1c",
        "on-tertiary-container": "#517cbc",
        "tertiary-fixed-dim": "#a8c8ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
