/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#7a7b7b",
        surface: "rgb(var(--surface) / <alpha-value>)",
        error: "rgb(var(--error) / <alpha-value>)",
        "error-container": "rgb(var(--error-container) / <alpha-value>)",
        warning: "rgb(var(--warning) / <alpha-value>)",
        "warning-container": "rgb(var(--warning-container) / <alpha-value>)",
        success: "rgb(var(--success) / <alpha-value>)",
        "success-container": "rgb(var(--success-container) / <alpha-value>)",
        info: "rgb(var(--info) / <alpha-value>)",
        "info-container": "rgb(var(--info-container) / <alpha-value>)",
        "on-secondary-fixed-variant": "#00497d",
        primary: "rgb(var(--primary) / <alpha-value>)",
        "secondary-fixed-dim": "#9ecaff",
        "surface-bright": "rgb(var(--surface-bright) / <alpha-value>)",
        "inverse-surface": "#e1e2e7",
        "inverse-on-surface": "#2e3134",
        "on-surface": "rgb(var(--on-surface) / <alpha-value>)",
        tertiary: "#a8c8ff",
        "on-secondary-fixed": "#001d36",
        "surface-container-low": "rgb(var(--surface-container-low) / <alpha-value>)",
        "surface-container-high": "rgb(var(--surface-container-high) / <alpha-value>)",
        "primary-fixed-dim": "#c6c6c7",
        secondary: "rgb(var(--secondary) / <alpha-value>)",
        background: "#111417",
        "tertiary-container": "#000e24",
        "on-tertiary-fixed-variant": "#114784",
        "tertiary-fixed": "#d5e3ff",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-container-lowest": "rgb(var(--surface-container-lowest) / <alpha-value>)",
        "inverse-primary": "#5d5f5f",
        "on-secondary-container": "#002b4d",
        "on-secondary": "rgb(var(--on-secondary) / <alpha-value>)",
        "surface-variant": "#323539",
        "on-error": "#690005",
        "on-background": "#e1e2e7",
        "surface-container-highest": "rgb(var(--surface-container-highest) / <alpha-value>)",
        "outline-variant": "rgb(var(--outline-variant) / <alpha-value>)",
        "on-primary-fixed-variant": "#454747",
        "surface-dim": "#111417",
        "surface-tint": "#c6c6c7",
        "on-tertiary-fixed": "#001b3c",
        "primary-container": "rgb(var(--primary-container) / <alpha-value>)",
        "primary-fixed": "#e2e2e2",
        outline: "#8f9095",
        "on-surface-variant": "rgb(var(--on-surface-variant) / <alpha-value>)",
        "on-tertiary": "#003061",
        "surface-container": "rgb(var(--surface-container) / <alpha-value>)",
        "secondary-fixed": "#d1e4ff",
        "secondary-container": "rgb(var(--secondary-container) / <alpha-value>)",
        "on-primary": "rgb(var(--on-primary) / <alpha-value>)",
        "on-primary-fixed": "#1a1c1c",
        "on-tertiary-container": "#517cbc",
        "tertiary-fixed-dim": "#a8c8ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        display: ["var(--font-display)", "Rajdhani", "Inter", "ui-sans-serif", "sans-serif"],
        headline: ["var(--font-editorial-serif)", "Cormorant Garamond", "Georgia", "serif"],
        body: ["var(--font-body)", "Inter", "sans-serif"],
        label: ["var(--font-body)", "Inter", "sans-serif"],
        data: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Courier New", "monospace"],
      },
    },
  },
  plugins: [],
};
