import type {
  AssetDefinition,
  CategoryOption,
  LiquidityProfile,
  LiquidityTier,
} from "@/components/tools/correlation/types";

export const CATEGORY_OPTIONS: CategoryOption[] = [
  {
    id: "emtialar",
    label: "Emtialar",
    description: "Enerji ve degerli metallerin en likit kontratlari.",
    universeHint: "Global emtia liderleri (top %5 likidite dilimi)",
  },
  {
    id: "kripto",
    label: "Kripto Varliklar",
    description: "Piyasa degeri ve hacim bazli en guclu coin seti.",
    universeHint: "Top market cap kripto varliklar (top %5)",
  },
  {
    id: "turk_hisse",
    label: "Turk Hisse Senetleri",
    description: "BIST30 ve benzeri yuksek hacimli hisseler.",
    universeHint: "BIST30 agirlikli en yuksek likidite grubu",
  },
  {
    id: "abd_hisse",
    label: "ABD Hisse Senetleri",
    description: "S&P100/Nasdaq lider mega-cap hisseler.",
    universeHint: "ABD buyuk olcekli hisselerde top %5 dilim",
  },
];

export const LIQUIDITY_TABLE: Record<LiquidityTier, LiquidityProfile> = {
  ultra: { liquidationDays: 1, marginAddOn: 0.01, slippageMultiplier: 1.0 },
  high: { liquidationDays: 2, marginAddOn: 0.02, slippageMultiplier: 1.05 },
  medium: { liquidationDays: 4, marginAddOn: 0.04, slippageMultiplier: 1.15 },
  low: { liquidationDays: 7, marginAddOn: 0.07, slippageMultiplier: 1.3 },
};

export const WINDOW_OPTIONS = [
  { key: "d30", label: "30G", size: 30 },
  { key: "d90", label: "90G", size: 90 },
  { key: "d250", label: "250G", size: 250 },
  { key: "y1", label: "1Y", size: 252 },
  { key: "y3", label: "3Y", size: 756 },
] as const;

export const ASSET_UNIVERSE: AssetDefinition[] = [
  {
    id: "xauusd",
    ticker: "XAUUSD",
    name: "Altin Spot",
    category: "emtialar",
    topPercentile: 2.4,
    benchmarkGroup: "Metals-Top",
    liquidityTier: "ultra",
    baseDrift: 0.00016,
    baseVol: 0.011,
    betaGlobal: 0.22,
    betaCategory: 0.68,
    jumpSensitivity: 0.8,
    gapSensitivity: 0.65,
  },
  {
    id: "xagusd",
    ticker: "XAGUSD",
    name: "Gumus Spot",
    category: "emtialar",
    topPercentile: 3.2,
    benchmarkGroup: "Metals-Top",
    liquidityTier: "high",
    baseDrift: 0.00014,
    baseVol: 0.014,
    betaGlobal: 0.26,
    betaCategory: 0.75,
    jumpSensitivity: 0.95,
    gapSensitivity: 0.8,
  },
  {
    id: "brent",
    ticker: "BRENT",
    name: "Brent Petrol",
    category: "emtialar",
    topPercentile: 2.8,
    benchmarkGroup: "Energy-Top",
    liquidityTier: "ultra",
    baseDrift: 0.00012,
    baseVol: 0.017,
    betaGlobal: 0.34,
    betaCategory: 0.82,
    jumpSensitivity: 1.2,
    gapSensitivity: 0.95,
  },
  {
    id: "wti",
    ticker: "WTI",
    name: "WTI Petrol",
    category: "emtialar",
    topPercentile: 3.9,
    benchmarkGroup: "Energy-Top",
    liquidityTier: "high",
    baseDrift: 0.00011,
    baseVol: 0.018,
    betaGlobal: 0.33,
    betaCategory: 0.8,
    jumpSensitivity: 1.25,
    gapSensitivity: 1.0,
  },
  {
    id: "btc",
    ticker: "BTC",
    name: "Bitcoin",
    category: "kripto",
    topPercentile: 1.1,
    benchmarkGroup: "Crypto-Large",
    liquidityTier: "ultra",
    baseDrift: 0.00035,
    baseVol: 0.03,
    betaGlobal: 0.62,
    betaCategory: 0.9,
    jumpSensitivity: 1.45,
    gapSensitivity: 1.3,
  },
  {
    id: "eth",
    ticker: "ETH",
    name: "Ethereum",
    category: "kripto",
    topPercentile: 1.7,
    benchmarkGroup: "Crypto-Large",
    liquidityTier: "ultra",
    baseDrift: 0.00032,
    baseVol: 0.034,
    betaGlobal: 0.68,
    betaCategory: 0.94,
    jumpSensitivity: 1.5,
    gapSensitivity: 1.35,
  },
  {
    id: "bnb",
    ticker: "BNB",
    name: "BNB",
    category: "kripto",
    topPercentile: 2.9,
    benchmarkGroup: "Crypto-Large",
    liquidityTier: "high",
    baseDrift: 0.00028,
    baseVol: 0.031,
    betaGlobal: 0.6,
    betaCategory: 0.86,
    jumpSensitivity: 1.3,
    gapSensitivity: 1.2,
  },
  {
    id: "sol",
    ticker: "SOL",
    name: "Solana",
    category: "kripto",
    topPercentile: 4.6,
    benchmarkGroup: "Crypto-Growth",
    liquidityTier: "high",
    baseDrift: 0.00037,
    baseVol: 0.04,
    betaGlobal: 0.72,
    betaCategory: 0.98,
    jumpSensitivity: 1.7,
    gapSensitivity: 1.45,
  },
  {
    id: "thyao",
    ticker: "THYAO",
    name: "Turk Hava Yollari",
    category: "turk_hisse",
    topPercentile: 2.1,
    benchmarkGroup: "BIST30",
    liquidityTier: "high",
    baseDrift: 0.00024,
    baseVol: 0.024,
    betaGlobal: 0.46,
    betaCategory: 0.85,
    jumpSensitivity: 1.15,
    gapSensitivity: 1.1,
  },
  {
    id: "garan",
    ticker: "GARAN",
    name: "Garanti BBVA",
    category: "turk_hisse",
    topPercentile: 1.9,
    benchmarkGroup: "BIST30",
    liquidityTier: "ultra",
    baseDrift: 0.0002,
    baseVol: 0.021,
    betaGlobal: 0.42,
    betaCategory: 0.8,
    jumpSensitivity: 1.05,
    gapSensitivity: 1.0,
  },
  {
    id: "kchol",
    ticker: "KCHOL",
    name: "Koc Holding",
    category: "turk_hisse",
    topPercentile: 2.5,
    benchmarkGroup: "BIST30",
    liquidityTier: "high",
    baseDrift: 0.00018,
    baseVol: 0.02,
    betaGlobal: 0.38,
    betaCategory: 0.76,
    jumpSensitivity: 0.95,
    gapSensitivity: 0.88,
  },
  {
    id: "asels",
    ticker: "ASELS",
    name: "Aselsan",
    category: "turk_hisse",
    topPercentile: 4.3,
    benchmarkGroup: "BIST30",
    liquidityTier: "medium",
    baseDrift: 0.00026,
    baseVol: 0.026,
    betaGlobal: 0.4,
    betaCategory: 0.78,
    jumpSensitivity: 1.18,
    gapSensitivity: 1.12,
  },
  {
    id: "aapl",
    ticker: "AAPL",
    name: "Apple",
    category: "abd_hisse",
    topPercentile: 1.2,
    benchmarkGroup: "SP100",
    liquidityTier: "ultra",
    baseDrift: 0.00025,
    baseVol: 0.017,
    betaGlobal: 0.51,
    betaCategory: 0.75,
    jumpSensitivity: 0.9,
    gapSensitivity: 0.72,
  },
  {
    id: "msft",
    ticker: "MSFT",
    name: "Microsoft",
    category: "abd_hisse",
    topPercentile: 1.1,
    benchmarkGroup: "SP100",
    liquidityTier: "ultra",
    baseDrift: 0.00024,
    baseVol: 0.016,
    betaGlobal: 0.48,
    betaCategory: 0.72,
    jumpSensitivity: 0.86,
    gapSensitivity: 0.7,
  },
  {
    id: "nvda",
    ticker: "NVDA",
    name: "NVIDIA",
    category: "abd_hisse",
    topPercentile: 2.8,
    benchmarkGroup: "Nasdaq100",
    liquidityTier: "ultra",
    baseDrift: 0.00034,
    baseVol: 0.028,
    betaGlobal: 0.62,
    betaCategory: 0.9,
    jumpSensitivity: 1.22,
    gapSensitivity: 1.1,
  },
  {
    id: "amzn",
    ticker: "AMZN",
    name: "Amazon",
    category: "abd_hisse",
    topPercentile: 3.2,
    benchmarkGroup: "SP100",
    liquidityTier: "ultra",
    baseDrift: 0.00027,
    baseVol: 0.021,
    betaGlobal: 0.57,
    betaCategory: 0.79,
    jumpSensitivity: 1.0,
    gapSensitivity: 0.82,
  },
  {
    id: "xom",
    ticker: "XOM",
    name: "Exxon Mobil",
    category: "abd_hisse",
    topPercentile: 2.6,
    benchmarkGroup: "SP100",
    liquidityTier: "ultra",
    baseDrift: 0.00019,
    baseVol: 0.018,
    betaGlobal: 0.49,
    betaCategory: 0.74,
    jumpSensitivity: 0.92,
    gapSensitivity: 0.76,
  },
  {
    id: "cvx",
    ticker: "CVX",
    name: "Chevron",
    category: "abd_hisse",
    topPercentile: 3.4,
    benchmarkGroup: "SP100",
    liquidityTier: "high",
    baseDrift: 0.00018,
    baseVol: 0.019,
    betaGlobal: 0.5,
    betaCategory: 0.73,
    jumpSensitivity: 0.94,
    gapSensitivity: 0.78,
  },
];

export function getAssetsByCategory(categoryId: CategoryOption["id"]): AssetDefinition[] {
  return ASSET_UNIVERSE.filter((asset) => asset.category === categoryId && asset.topPercentile <= 5).sort(
    (left, right) => left.topPercentile - right.topPercentile
  );
}
