const TR_REPLACEMENTS: Array<[string, string]> = [
  ["Urun", "Ürün"],
  ["urun", "ürün"],
  ["Acik", "Açık"],
  ["acik", "açık"],
  ["Acilisinda", "Açılışında"],
  ["acilisinda", "açılışında"],
  ["Sifir", "Sıfır"],
  ["sifir", "sıfır"],
  ["Cozum", "Çözüm"],
  ["cozum", "çözüm"],
  ["Cozumleri", "Çözümleri"],
  ["cozumleri", "çözümleri"],
  ["Cozumler", "Çözümler"],
  ["cozumler", "çözümler"],
  ["Gorsel", "Görsel"],
  ["gorsel", "görsel"],
  ["Ongoru", "Öngörü"],
  ["ongoru", "öngörü"],
  ["Ongoruler", "Öngörüler"],
  ["ongoruler", "öngörüler"],
  ["Guven", "Güven"],
  ["guven", "güven"],
  ["Arac", "Araç"],
  ["arac", "araç"],
  ["Araclar", "Araçlar"],
  ["araclar", "araçlar"],
  ["Araclari", "Araçları"],
  ["araclari", "araçları"],
  ["Yatirim", "Yatırım"],
  ["yatirim", "yatırım"],
  ["Karsilastirma", "Karşılaştırma"],
  ["karsilastirma", "karşılaştırma"],
  ["Portfoy", "Portföy"],
  ["portfoy", "portföy"],
  ["Piyasalari", "Piyasaları"],
  ["piyasalari", "piyasaları"],
  ["Kiymetler", "Kıymetler"],
  ["kiymetler", "kıymetler"],
  ["Borclanma", "Borçlanma"],
  ["borclanma", "borçlanma"],
  ["Fonlari", "Fonları"],
  ["fonlari", "fonları"],
  ["Kaldiracli", "Kaldıraçlı"],
  ["kaldiracli", "kaldıraçlı"],
  ["islemleri", "işlemleri"],
  ["Islemleri", "İşlemleri"],
  ["islemlerinde", "işlemlerinde"],
  ["Islemlerinde", "İşlemlerinde"],
  ["dayali", "dayalı"],
  ["Dayali", "Dayalı"],
  ["altin", "altın"],
  ["Altin", "Altın"],
  ["gumus", "gümüş"],
  ["Gumus", "Gümüş"],
  ["kopyalandi", "kopyalandı"],
  ["guncellendi", "güncellendi"],
  ["Canli", "Canlı"],
  ["canli", "canlı"],
];

export function normalizeTurkishText(input: string): string {
  // 1) Apply a deterministic replacement list over the full text.
  return TR_REPLACEMENTS.reduce((output, pair) => {
    // 2) Replace whole-word matches to avoid accidental partial changes.
    const pattern = new RegExp(`\\b${pair[0]}\\b`, "g");
    return output.replace(pattern, pair[1]);
  }, input);
}
